# Generated by Django 4.2.10 on 2025-08-22 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0002_remove_invoiceitem_product_invoiceitem_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
