# Generated by Django 4.2.10 on 2025-08-23 05:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("invoices", "0003_customer_is_active"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="invoice",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="invoice",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterUniqueTogether(
            name="invoice",
            unique_together={("owner", "number", "is_active")},
        ),
    ]
