# Generated by Django 4.2.10 on 2025-08-23 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0004_alter_invoice_unique_together_invoice_is_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="supplier_ref",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
