# Generated by Django 4.2.10 on 2025-08-23 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0005_invoice_supplier_ref"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="delivery_note_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="despatch_doc_no",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="invoice",
            name="other_ref",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
