# Generated by Django 4.2.10 on 2025-08-23 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "invoices",
            "0006_invoice_delivery_note_date_invoice_despatch_doc_no_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="destination_other",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="invoice",
            name="dispatched_through",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
