# Generated by Django 4.2.10 on 2025-08-23 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0007_invoice_destination_other_invoice_dispatched_through"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="invoice",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("owner", "number"),
                name="unique_active_invoice_number_per_owner",
            ),
        ),
    ]
