# Generated by Django 4.2.10 on 2025-08-23 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0008_alter_invoice_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="invoice",
            options={},
        ),
        migrations.RemoveConstraint(
            model_name="invoice",
            name="unique_active_invoice_number_per_owner",
        ),
    ]
