# Generated by Django 4.2.10 on 2025-08-23 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0009_alter_invoice_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoiceitem",
            name="rate_tax_ex",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
