# Generated by Django 4.2.10 on 2025-08-23 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0010_invoiceitem_rate_tax_ex"),
    ]

    operations = [
        migrations.RenameField(
            model_name="invoice",
            old_name="dispatched_through",
            new_name="despatched_through",
        ),
    ]
