# Generated by Django 5.1.3 on 2025-08-25 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0011_rename_dispatched_through_invoice_despatched_through"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="bank_branch",
            field=models.CharField(default="", max_length=100),
        ),
    ]
