# Generated by Django 4.2.10 on 2025-08-23 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="item",
            old_name="active",
            new_name="is_active",
        ),
    ]
