# Generated by Django 4.2.10 on 2025-08-23 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_rename_active_item_is_active"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="item",
            unique_together=set(),
        ),
    ]
